server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: laravel
    static_configs:
      - targets:
          - localhost
        labels:
          job: laravel
          app: synapticore
          __path__: /var/www/html/storage/logs/*.log
    
    pipeline_stages:
      - json:
          expressions:
            level: level
            message: message
            context: context
            timestamp: datetime
      
      - labels:
          level:
      
      - timestamp:
          source: timestamp
          format: "2006-01-02T15:04:05.000000Z07:00"
  
  - job_name: containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: containers
          __path__: /var/lib/docker/containers/*/*log
    
    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            time: time
      
      - regex:
          expression: '(?P<container_name>synapticore_[^/]+)'
          source: filename
      
      - labels:
          container_name:
          stream: