global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'synapticore-monitor'
    environment: 'development'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          instance: 'prometheus'

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888', 'otel-collector:8889']
        labels:
          instance: 'otel-collector'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          instance: 'node'

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          instance: 'redis'

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
        labels:
          instance: 'postgres'

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
        labels:
          instance: 'nginx'

  - job_name: 'app'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['app:9000']
        labels:
          instance: 'laravel'